language: node_js
node_js:
- '0.10'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: MIcNierVKGnBMJ75NUWBAGpw9SLfNbVMOcFCj0e2jSqfkSAyadkQvlnSUxO20xOgUz67aSnTa/w+njyyEC3etxrj626Zx02GIBzOfo9EMlv+6yE19z4LYRbWibFzDaZLohCc0xTR9SX8DxrCC1wItFDRjY/T7nSEDyF26jKyPRhAOq1IvtT1MhlLf4qmpDIBCdw60V1X3VgakrmcKdGLe/BWV6uvlHmWP3ZLqahhi3mVKR1raQM6C63F7VR4supRtPEhr+5e2PkuLm3FxzBMjkOWRJs2RRn6iLhMD5lOrwYhvWmDNuDWpQ3MlQxcPbMhaVbJWvbfFuE9pKixp7vwRwKSeDxfVGdnNcxyWb4BzMYwDtDNcCgU+mOGdaqljoTw51FLByi5FaI0lzqjSOvzaJ/QSk+G3E39T4sASTs5H9sbmfCFKgKCIGjINDxbtZmJfEqdqmqVIL3m1OKOYO9fZ3GIa9oncg1GigBUTCkiIKwKFrGjDUI/zAHJd2PGjgQnUyg415n9Wp8iDK0IbwOR2Uh3j1fRCm0kXy/04qbCcSazNCOaA3y/A5rY51zaqzXhTPeApFYTcz6hEXRebU0GYE1clnFXk0T8mK2j0DsigkdFzDVuOlMlaUXzyw1HapYPP0KjY0bI9cB7a6RREbFD9khBnsv093Lr4xf2M+0oHr8=
  app: ars-ctf
  on:
    repo: akhdani/capture-the-flag
