language: node_js
node_js:
- '0.10'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: F5EJk/FlACx4JYc+//y5I3fiPcG1RjiCCLceTHAatiYQJXbxoWAYRxzMdTvdOByWEGo8ow1qzFio7RrYaKkMT94xUxaYSq+0agQTErzM9bHwysd91gxCfnBg4Ixrd1UwTefbGsbEcoCcYPMfNHjBYz2l3dwUjtYehbtbO6G8SyWMxufNO48UblYVMUk4748qkLuf7XDO5FzjZnpH36tj/GIhf8TzRLgyLfnVddR1Lr+8KqMLABHKqyzmSIgbkXF/1YC6y24lYHoppIy7bX0xGeYAcJdhVssXqiY9+VoyjuINJg9yYMSOfiKQXQN4LlsRSljS6dddfNnJ8ielI4FP1CFllJ6BFz4mo5hwiFUTGO4HkUU0OP+gxB7uMsISlum4mvWlwgExMY69ae5zFEFHN4fQb1o97jPcko+oTqG+KeuWfpLj0/S/P1fxaJzO1ydBpZ57VNVBWEqyCFn1xXHMZRBQwNujeyKuwnGW2p70RQTHfF6pI9uYwDtk+zUF/ZJpWMKbMOdwopKrW3TwXoh72OwrfZ8T2KhXxS/huMU44fRnsocD27OB4O1wmSc01c7FSTN2JrCYKL7CPxh/7wdsgYAgEJbbTkcglKvR1aKOXTRs+3HI5mghaMEy+TuDyTdgvEFcVCEtDz8wWOgrrsiTN3/7mwf+pzdz2LrrFEttddQ=
  app: ars-capture-the-flag
  on:
    repo: akhdani/capture-the-flag
notifications:
  email: false
